import test from 'node:test';import assert from 'node:assert/strict';
import {story,start,routeNode,endings,scenes,wardrobes} from '../story.js';import {fresh,current,advance,choose,availableRoutes,pack,unpack,beginChallenge,finishChallenge} from '../engine.js';
function play(policy,route=2,accept=0){let s=fresh('测试玩家');let count=0;while(!s.ending&&count++<400){const n=current(s);if(s.reply){advance(s);continue;}if(n.game){assert.ok(finishChallenge(s,true));}else if(n.routeChoice){assert.ok(choose(s,route));}else if(n.choices){const i=n.chapter===5?accept:policy(n);assert.ok(choose(s,i));}else assert.ok(advance(s));}assert.ok(s.ending);return s;}
test('Every story node has a valid path, no dangling links',()=>{for(const n of Object.values(story)){assert.ok(scenes[n.scene]&&wardrobes[n.wardrobe]);if(n.next)assert.ok(story[n.next],n.id);assert.ok(n.next||n.ending||n.routeChoice||n.choices?.some(c=>c.effect.ending),n.id);}});
test('All three endings are reachable through normal choices',()=>{assert.equal(play(()=>0,0).ending,'y');assert.equal(play(n=>n.chapter===1?0:1,1).ending,'z');assert.equal(play(()=>2,2).ending,'friend');});
test('Player may refuse romance inside either character route',()=>{assert.equal(play(()=>0,0,1).ending,'friend');assert.equal(play(n=>n.chapter===1?0:1,1,1).ending,'friend');});
test('Insufficient connection locks romance and never friendship',()=>{const s=fresh();s.node=routeNode;assert.equal(choose(s,0),false);assert.equal(choose(s,1),false);assert.equal(availableRoutes(s)[2].locked,false);assert.ok(choose(s,2));});
test('Choice cannot be applied twice while reaction is displayed',()=>{const s=fresh();s.node=Object.values(story).find(n=>n.choices).id;choose(s,0);const score=s.y;assert.equal(choose(s,0),false);assert.equal(s.y,score);});
test('Save and resume preserve branch, reaction, name, photo and ending',()=>{const s=fresh('<小雨>');s.node=Object.values(story).find(n=>n.choices).id;choose(s,0);assert.deepEqual(unpack(pack(s)),s);const restored=unpack(pack(s));advance(restored);assert.equal(restored.node,current(s).next);for(const type of ['y','z','friend']){const e=play(type==='z'?n=>n.chapter===1?0:1:()=>0,type==='y'?0:type==='z'?1:2);assert.deepEqual(unpack(pack(e)),e);}});
test('Corrupt and obsolete save payloads are rejected',()=>{for(const raw of ['oops','null','{}',pack({...fresh(),version:1}),pack({...fresh(),node:'missing'}),pack({...fresh(),y:NaN}),pack({...fresh(),ending:'unknown'}),pack({...fresh(),log:[{speaker:3,text:4}]})])assert.equal(unpack(raw),null);});
test('Exhaust all 729 common choice combinations, every available route terminates',()=>{let checked=0;function walk(s,depth=0){assert.ok(depth<350);if(s.ending){assert.ok(endings[s.ending]);checked++;return;}const n=current(s);if(!s.reply&&n.game){assert.ok(finishChallenge(s,true));walk(s,depth+1);}else if(!s.reply&&(n.choices||n.routeChoice)){const opts=n.routeChoice?availableRoutes(s):n.choices;for(let i=0;i<opts.length;i++){if(opts[i].locked)continue;const c=structuredClone(s);assert.ok(choose(c,i));walk(c,depth+1);}}else{assert.ok(advance(s));walk(s,depth+1);}}walk(fresh());assert.ok(checked>729);console.log('Verified complete paths:',checked);});
import {createChallenge,actChallenge,challengeResult,validChallenge} from '../minigames.js';
test('All three challenges block accidental advance but permit a skip',()=>{for(const id of ['focus','packing','archive']){const s=fresh();s.node=Object.values(story).find(n=>n.game===id).id;assert.equal(advance(s),false);assert.equal(finishChallenge(s),false);assert.ok(finishChallenge(s,true));assert.equal(s.games[id].status,'skip');assert.equal(finishChallenge(s,true),false);assert.ok(advance(s));}});
test('Focus uses shot timing, distinguishes outcomes and limits shots',()=>{for(const [shots,status] of [[[50,39,99],'success'],[[10,50,90],'rough']]){const c=createChallenge('focus');for(const position of shots)assert.ok(actChallenge(c,{type:'shoot',position}));assert.equal(challengeResult(c).status,status);assert.equal(actChallenge(c,{type:'shoot',position:50}),false);assert.ok(validChallenge(c));}assert.equal(actChallenge(createChallenge('focus'),{type:'shoot',position:NaN}),false);});
test('Packing prevents collision and corridor expansion; rotation and solution work',()=>{const c=createChallenge('packing');actChallenge(c,{type:'place',row:0,col:3});assert.equal(c.placed.length,0);actChallenge(c,{type:'place',row:0,col:0});actChallenge(c,{type:'place',row:0,col:0});assert.equal(c.placed.length,1);actChallenge(c,{type:'place',row:0,col:1});actChallenge(c,{type:'place',row:2,col:1});assert.equal(challengeResult(c).status,'success');assert.ok(validChallenge(c));const r=createChallenge('packing');actChallenge(r,{type:'rotate'});actChallenge(r,{type:'place',row:0,col:0});assert.equal(r.placed[0].rotated,true);assert.ok(validChallenge(r));});
test('Memory matches pairs and records mismatches without double-flipping',()=>{const c=createChallenge('archive',()=>.5);assert.ok(validChallenge(c));actChallenge(c,{type:'flip',index:0});assert.equal(actChallenge(c,{type:'flip',index:0}),false);const different=c.cards.findIndex(x=>x!==c.cards[0]);actChallenge(c,{type:'flip',index:different});assert.equal(c.turns,1);assert.equal(c.matched.length,0);assert.equal(c.open.length,2);const next=c.cards.findIndex((_,i)=>!c.open.includes(i));actChallenge(c,{type:'flip',index:next});assert.deepEqual(c.open,[next]);const mate=c.cards.findIndex((v,i)=>v===c.cards[next]&&i!==next);actChallenge(c,{type:'flip',index:mate});assert.equal(c.matched.length,2);for(let v=0;v<4;v++)c.cards.forEach((x,i)=>{if(x===v&&!c.matched.includes(i))actChallenge(c,{type:'flip',index:i});});assert.equal(c.matched.length,8);assert.ok(challengeResult(c));});
test('Partial challenge state survives reload, and completed result advances exactly once',()=>{for(const id of ['focus','packing','archive']){const s=fresh();s.node=Object.values(story).find(n=>n.game===id).id;const c=beginChallenge(s);if(id==='focus')actChallenge(c,{type:'shoot',position:50});if(id==='packing')actChallenge(c,{type:'place',row:0,col:0});if(id==='archive')actChallenge(c,{type:'flip',index:0});assert.deepEqual(unpack(pack(s)),s);assert.ok(finishChallenge(s,true));assert.deepEqual(unpack(pack(s)),s);assert.ok(advance(s));assert.equal(s.challenge,null);}
 const s=fresh();s.node=Object.values(story).find(n=>n.game==='focus').id;const c=beginChallenge(s);for(let i=0;i<3;i++)actChallenge(c,{type:'shoot',position:50});assert.ok(finishChallenge(s));assert.equal(s.games.focus.status,'success');assert.equal(finishChallenge(s),false);assert.ok(advance(s));});
test('Invalid challenge saves are rejected',()=>{const s=fresh();assert.equal(unpack(pack({...s,challenge:createChallenge('focus')})),null);assert.equal(unpack(pack({...s,games:{alien:{}}})),null);const c=createChallenge('packing');c.placed=[{id:'bag',row:0,col:3,rotated:false}];assert.equal(validChallenge(c),false);const a=createChallenge('archive');a.cards=[0,0,0,0,0,0,0,0];assert.equal(validChallenge(a),false);});
